# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of your contact.', max_length=50)),
                ('email', models.EmailField(blank=True, help_text="The contact's email address.", max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='The phone number of your contact.', max_length=12, null=True)),
                ('contact_type', models.CharField(blank=True, choices=[('i', 'Indvidual/Donor'), ('p', 'Potential Donor'), ('v', 'Volunteer'), ('c', 'Corporation/Foundation'), ('g', 'Grant Resource')], default='i', help_text='Book availability', max_length=1)),
                ('notes', models.TextField(blank=True, help_text='Any extra notes for this contact.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this organization.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Any extra notes for this organization.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Shorthand for referring to this project.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Any extra notes for this project.', max_length=1000)),
                ('associated', models.ManyToManyField(help_text='Who is associated with this project?', to='contact.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.Organization'),
        ),
    ]
