# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20171031_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='The phone number of your contact.', max_length=20, null=True),
        ),
    ]
