# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20171031_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', '-complete']},
        ),
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.BooleanField(help_text='Is this task complete?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, help_text='What is the deadline for this task?', null=True),
        ),
    ]
