# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20171105_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcontactassoc',
            name='tag_type',
            field=models.CharField(choices=[('as', 'Assigned'), ('ta', 'Target'), ('na', 'Non-Specified Role')], default='n/', max_length=2),
        ),
    ]
