# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_auto_20171129_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='associated',
        ),
        migrations.AddField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(help_text='Who is associated with this task?', related_name='tasks', through='contact.TaskContactAssoc', to='contact.Contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='proj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='contact.Project'),
        ),
    ]
