# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_auto_20171211_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContactAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('as', 'Assigned'), ('cr', 'Creator'), ('na', 'Unspecified')], default='na', max_length=2)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_assocs', to='contact.Contact')),
            ],
            options={
                'ordering': ['con', 'proj', 'tag_type'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, help_text='What is the deadline for this task?', null=True),
        ),
        migrations.AlterField(
            model_name='taskcontactassoc',
            name='tag_type',
            field=models.CharField(choices=[('as', 'Assigned'), ('cr', 'Creator'), ('ta', 'Target'), ('na', 'Unspecified')], default='na', max_length=2),
        ),
        migrations.AddField(
            model_name='projectcontactassoc',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_assocs', to='contact.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='contacts',
            field=models.ManyToManyField(help_text='Who is associated with this task?', related_name='projects', through='contact.ProjectContactAssoc', to='contact.Contact'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcontactassoc',
            unique_together=set([('con', 'proj')]),
        ),
    ]
