# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_auto_20180110_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'complete'], 'permissions': (('task_view_all', 'View all tasks.'), ('task_view_related', 'View related tasks.'), ('task_assign', 'Assign contacts to tasks'), ('task_assign_admin', 'Assign contacts to admined tasks'), ('task_add_admin', 'Add tasks to admined projects'), ('task_change_admin', 'Change admined project tasks'), ('task_delete_admin', 'Delete admined project tasks'), ('task_down_sum_all', 'Download overall task summary.'), ('task_down_sum_each', 'Download individual task summaries.'), ('task_down_sum_related', 'Download related task summaries.'))},
        ),
    ]
