# Generated by Django 2.0.1 on 2018-02-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0025_auto_20180114_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this event / workshop.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Any extra notes for this event / workshop.', max_length=2500)),
                ('contacts', models.ManyToManyField(related_name='events', to='contact.Contact')),
            ],
            options={
                'permissions': (('event_view_all', 'View all events / workshops.'), ('event_down_sum_all', 'Download events / workshops summaries.')),
            },
        ),
        migrations.AlterField(
            model_name='contacttypetag',
            name='tag_type',
            field=models.CharField(choices=[('do', 'Donor'), ('pr', 'Prospect'), ('vo', 'Volunteer'), ('_f', 'Corporate / Foundation'), ('_g', 'Grant Resource')], default='pr', max_length=2),
        ),
    ]
