# Generated by Django 2.0.1 on 2018-02-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_auto_20180207_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='events',
            field=models.ManyToManyField(related_name='contacts', to='contact.Event'),
        ),
    ]
