# Generated by Django 2.1.4 on 2018-12-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0029_auto_20180210_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contact.Event'),
        ),
    ]
