# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20171030_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacttypetag',
            options={'ordering': ['contact', '-tag_type']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='The phone number of your contact.', max_length=16, null=True),
        ),
    ]
