# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0011_auto_20171105_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskcontactassoc',
            name='tag_type',
            field=models.CharField(choices=[('as', 'Assigned'), ('ta', 'Target'), ('na', 'Non-Specified Role')], default='na', max_length=2),
        ),
    ]
