# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20171106_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'complete']},
        ),
        migrations.AlterModelOptions(
            name='taskcontactassoc',
            options={'ordering': ['con', 'task', 'tag_type']},
        ),
        migrations.AlterField(
            model_name='taskcontactassoc',
            name='tag_type',
            field=models.CharField(choices=[('as', 'Assigned'), ('cr', 'Creator'), ('ta', 'Target'), ('na', 'Non-Specified Role')], default='na', max_length=2),
        ),
    ]
